version: "3.8"
services:
  mongo:
    image: mongo:6
    platform: linux/arm64/v8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mongo_data: